server:
  port: 8831 # 服务端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
spring:
  cloud:
    config:
      enabled: false
  application:
    name: web-service # 服务名称

health.config.enabled: false

app.default.language: zh_CN
app.config.internal.api.secret: pq0194mxoqfh48L362G6R09T737E273X

hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.threadpool.default.coreSize: 10
hystrix.threadpool.default.maximumSize: 50
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 100
hystrix.threadpool.default.allowMaximumSizeToDivergeFromCoreSize: true

ribbon.ReadTimeout: 3000
ribbon.ConnectTimeout: 3000

# disable Ribbon's circuit breaker and rely soley on Hystrix.
# this helps to avoid confusion.
# see https://github.com/Netflix/ribbon/issues/15
niws:
  loadbalancer:
    availabilityFilteringRule:
      filterCircuitTripped: false # 默认为 true, 导致 IndexOutOfBoundsException错误

# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  ## 配置httpclient线程池
  httpclient:
    enabled: true
  okhttp:
    enabled: false

management:
  server:
    port: 8031
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 1m
    web:
      server:
        auto-time-requests: true
  #    distribution:
  #      percentiles-histogram[http.server.requests]: true
  #      percentiles:
  #        http.server.requests: 0.95, 0.9
  #      sla:
  #        http.server.requests: 10ms, 100ms

  endpoints:
    web:
      exposure:
        include: "prometheus,health,metrics,httptrace,hystrix.stream"

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR


---
spring:
  profiles: test


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://10.0.0.35:8761/eureka/


---
spring:
  profiles: oversea

app.default.language: en_US


eureka.client.serviceUrl.defaultZone: {{ eureka_client_serviceUrl_defaultZone }}

logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR

---
spring:
  profiles: ningxia

app.default.language: zh_CN


eureka.client.serviceUrl.defaultZone: {{ eureka_client_serviceUrl_defaultZone }}

logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR
---
spring:
  profiles: ningxia-dev

app.default.language: zh_CN


eureka.client.serviceUrl.defaultZone: {{ eureka_client_serviceUrl_defaultZone }}

logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR
---
spring:
  profiles: china

app.default.language: zh_CN

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.0.30:8761/eureka/,http://10.0.0.39:8761/eureka/

logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR


---
spring:
  profiles: test-oversea

app.default.language: en_US

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR